// -----------------------------------------------------------------------------
// axi2apb4_driver.sv
// Active AXI-Lite master driver.
// Drives only AXI-Lite side; APB side is generated by the bridge RTL.
// -----------------------------------------------------------------------------

class axi2apb4_driver extends uvm_driver #(axi2apb4_trans);

    `uvm_component_utils(axi2apb4_driver)

    virtual axi2apb4_axi_lite_if vif;

    function new(string name = "axi2apb4_driver", uvm_component parent = null);
        super.new(name, parent);
    endfunction

    function void build_phase(uvm_phase phase);
        super.build_phase(phase);
        if (!uvm_config_db#(virtual axi2apb4_axi_lite_if)::get(this, "", "axi_vif", vif)) begin
            `uvm_fatal(get_type_name(), "Failed to get axi_vif from uvm_config_db")
        end
    endfunction

    task run_phase(uvm_phase phase);
        axi2apb4_trans tr;

        drive_idle();
        wait_reset_done();

        forever begin
            seq_item_port.get_next_item(tr);
            `uvm_info(get_type_name(), {"Driving ", tr.convert2string()}, UVM_MEDIUM)
            if (tr.write) begin
                drive_write(tr);
            end else begin
                drive_read(tr);
            end
            seq_item_port.item_done();
        end
    endtask

    task wait_cycles(input int unsigned n);
        repeat (n) @(posedge vif.ACLK);
    endtask

    task wait_reset_done();
        @(posedge vif.ACLK);
        wait (vif.ARESETn === 1'b1);
        repeat (2) @(posedge vif.ACLK);
    endtask

    task drive_idle();
        vif.AWADDR  <= '0;
        vif.AWPROT  <= '0;
        vif.AWVALID <= 1'b0;
        vif.WDATA   <= '0;
        vif.WSTRB   <= '0;
        vif.WVALID  <= 1'b0;
        vif.BREADY  <= 1'b0;
        vif.ARADDR  <= '0;
        vif.ARPROT  <= '0;
        vif.ARVALID <= 1'b0;
        vif.RREADY  <= 1'b0;
    endtask

    task drive_aw(input axi2apb4_trans tr);
        wait_cycles(tr.aw_delay);
        vif.AWADDR  <= tr.addr;
        vif.AWPROT  <= tr.prot;
        vif.AWVALID <= 1'b1;
        do @(posedge vif.ACLK); while (!vif.AWREADY);
        vif.AWVALID <= 1'b0;
        vif.AWADDR  <= '0;
        vif.AWPROT  <= '0;
    endtask

    task drive_w(input axi2apb4_trans tr);
        wait_cycles(tr.w_delay);
        vif.WDATA  <= tr.wdata;
        vif.WSTRB  <= tr.wstrb;
        vif.WVALID <= 1'b1;
        do @(posedge vif.ACLK); while (!vif.WREADY);
        vif.WVALID <= 1'b0;
        vif.WDATA  <= '0;
        vif.WSTRB  <= '0;
    endtask

    task drive_write(input axi2apb4_trans tr);
        vif.BREADY <= 1'b0;

        fork
            drive_aw(tr);
            drive_w(tr);
        join

        wait (vif.BVALID === 1'b1);
        wait_cycles(tr.bready_delay);
        vif.BREADY <= 1'b1;
        do @(posedge vif.ACLK); while (!(vif.BVALID && vif.BREADY));
        vif.BREADY <= 1'b0;
    endtask

    task drive_read(input axi2apb4_trans tr);
        vif.RREADY <= 1'b0;

        wait_cycles(tr.ar_delay);
        vif.ARADDR  <= tr.addr;
        vif.ARPROT  <= tr.prot;
        vif.ARVALID <= 1'b1;
        do @(posedge vif.ACLK); while (!vif.ARREADY);
        vif.ARVALID <= 1'b0;
        vif.ARADDR  <= '0;
        vif.ARPROT  <= '0;

        wait (vif.RVALID === 1'b1);
        wait_cycles(tr.rready_delay);
        vif.RREADY <= 1'b1;
        do @(posedge vif.ACLK); while (!(vif.RVALID && vif.RREADY));
        vif.RREADY <= 1'b0;
    endtask

endclass
